# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campagna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('rss', models.CharField(max_length=255)),
                ('api', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=255)),
                ('fbad', models.CharField(max_length=255)),
                ('fbid', models.CharField(max_length=255, unique=True)),
                ('fbdate', models.CharField(max_length=255)),
                ('elaborato', models.BooleanField(default=False)),
                ('campagna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='leadbit.Campagna')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('raw', models.TextField(max_length=1000)),
                ('response', models.TextField(max_length=100)),
                ('successo', models.BooleanField()),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='leadbit.Lead')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
