# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadbit', '0003_request_api'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campagna',
            options={'ordering': ('-created',), 'verbose_name_plural': 'campagne'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ('-created',), 'verbose_name_plural': 'Richieste'},
        ),
        migrations.AddField(
            model_name='campagna',
            name='prodotto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campagna',
            name='qta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campagna',
            name='tipologia',
            field=models.CharField(blank=True, choices=[(1, b'LEADBIT'), (2, b'PANNELLO')], default=1, max_length=255),
        ),
    ]
