# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadbit', '0004_auto_20170410_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campagna',
            name='tipologia',
            field=models.IntegerField(blank=True, choices=[(1, b'LEADBIT'), (2, b'PANNELLO')], default=1, max_length=255),
        ),
    ]
